# --- VDN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 10000000

runner: "parallel"
batch_size_run: 32

buffer_size: 300000

# update the target network every {} episodes
target_update_interval: 2000

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "vdn"

name: "vdn_smac_parallel"
